### ISSUE TITLE
Note: Use horizontal layout whenever possible

### ISSUE THREAD

**Issue by gardnerkevin** [dan-massey/maf-2016#19]
We love how “The MAFistas” section collapses into 3 clickable panels on smaller screens. We’d like to organize content horizontally like this wherever possible. 

We want to use this same feature — even on the wide desktop version — for every section we can. This includes:

1. The MAFistas
2. Our Clients
3. Our Partners
4. 2015 Highlights
5. Our Financials
6. Looking Ahead
	
These sections should follow this general format:

![screen shot 2016-03-25 at 5 15 27 pm](https://cloud.githubusercontent.com/assets/7604224/14056731/3639a5f4-f2ad-11e5-94b2-a766fe6a5efb.png)

One photo + text (+ data point — where applicable) should show by default, and users should move to the second and third panels by clicking the buttons.

**Comment by billyroh** [comment]
Hi! What's the reasoning for wanting to use tabs even on desktop? We think it's good to show all three things at once on desktop for two reasons:

1. There's ample space, so it won't feel too crowded.
2. If we hide content behind tabs, people are less likely to see it.

If you feel very strongly about this, we can make it all tabs, but I would advise against it.

**Comment by gardnerkevin** [comment]
Hi Billy, thanks for sharing your feedback!

We'll follow your advice and stick to showing all 3 panels at once -- except for one section: We'd like to use tabs (even on desktop) for "Our Clients," showing the first tab by default, since the text for these is quite a bit longer than other sections. 

How does that sound?
