### ISSUE TITLE
"A Word from Our CEO" Feedback

### ISSUE THREAD

**Issue by gardnerkevin** [dan-massey/maf-2016#21]
- [x] Distribute text more evenly across the page
- [x] Alter the justification so it looks consistent when stacked on smaller screens

**Comment by dan-massey** [comment]
Hi Kevin, leaving this issue open. The styling on this section has changed, but we will probably want to revisit at the end and add some polish.

**Comment by gardnerkevin** [comment]
Hi there, noticed another edit needed:

- [ ] Jose’s quote, paragraph 2: Delete the words “every year ” from this sentence (just before the dash)
